<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>My Bioskop</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="../../../../../public/css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!">My Bioskop</a>
            </div>
        </nav>
        <!-- Header-->
        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <center><h1>FILM</h1>
                <br></br>
                <div class="row gx-4 gx-lg-5 row-cols-1 row-cols-md-3 row-cols-xl-5 justify-content-center">
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="../../../../../public/img/thenun.jpeg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">The Nun</h5>
                                    <!-- Product price-->
                                    Rp. 35.000
                                    <br></br>
                                    15:15:00
                                </div>
                            </div>
                            <!-- Product actions
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
                            </div> -->
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="../../../../../public/img/annabelle.jpeg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Annabelle Creation</h5>
                                    <!-- Product price-->
                                    Rp. 35.000
                                     <!--jam tayang-->
                                     <br></br>
                                     12:35:30
                                </div>
                            </div>
                            <!-- Product actions
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                            </div> -->
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="../../../../../public/img/conjuring.jpeg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">The Conjuring</h5>
                                    <!-- Product price-->
                                    Rp. 35.000
                                     <!--jam tayang-->
                                    <br></br>
                                    17:50:00
                                </div>
                            </div>
                            <!-- Product actions
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                            </div> -->
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="../../../../../public/img/gonjiam.jpeg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Gonjiam Haunted Asylum</h5>
                                    <!-- Product price-->
                                    Rp. 35.000
                                     <!--jam tayang-->
                                    <br></br> 
                                    15:12:00
                                </div>
                            </div>
                            <!-- Product actions
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                            </div> -->
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card h-80">
                            <!-- Product image-->
                            <img class="card-img-top" src="../../../../../public/img/the_nun2.jpeg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Gonjiam Haunted Asylum</h5>
                                    <!-- Product price-->
                                    Rp. 35.000
                                     <!--jam tayang-->
                                    <br></br> 
                                    15:12:00
                                </div>
                            </div>
                            <!-- Product actions
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                            </div> -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="container px-4 px-lg-5 mt-5">
                <center><h1>PILIH KURSI</h1></center>
                <br>
                <div class="row gx-4 gx-lg-5 row-cols-5 row-cols-md-3 row-cols-xl-5 justify-content-center">
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto " @click="isActive = !isActive" :class="activeClass" >A1</a></div>
                        </div>
                        <script src="script.js"></script>
                    </div>
                    
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >A2</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >A3</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >A4</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >A5</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >B1</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >B2</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >B3</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >B4</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >B5</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >C1</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >C2</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >C3</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >C4</a></div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" >C5</a></div>
                        </div>
                    </div>
                </div>  
                <br>
                <br><br><br>
                <div class="col mb-5">
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-success mt-auto" href="http://localhost:8081/MyBioskop/module/Application/view/application/index/invoice.phtml#!">Submit</a></div>
                        </div>
                    </div>  
            </div>
        </section>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
        <script>
            $(document).ready(function () {
                $('.btn-update-status').on('click', function (event) {
                    event.preventDefault();

                    // Dapatkan nilai film_id dan status dari data-attributes atau metode lainnya
                    var filmId = $(this).data('film-id');
                    var status = 'paid'; // Gantilah dengan cara mendapatkan nilai status yang sesuai

                    // Kirim permintaan Ajax
                    $.ajax({
                        type: 'GET',
                        url: '/update-status', // Sesuaikan dengan URL endpoint Anda
                        data: {
                            film_id: filmId,
                            status: status
                        },
                        success: function (response) {
                            // Handle respon dari server (jika diperlukan)
                            console.log(response);

                            // Contoh: Ubah warna tombol menjadi hijau setelah berhasil
                            $(event.target).css('background-color', 'green');
                        },
                        error: function (error) {
                            // Handle error (jika diperlukan)
                            console.error(error);
                        }
                    });
                });
            });
        </script>
    </body>
  
</html>
